### ISSUE TITLE
Two repos

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/poa-governance-notifications#1]
We have an old repo https://github.com/poanetwork/poa-governance-notifications
and new repo.
Old repo has a good name but outdated code. Let's delete the old one and rename current
Thoughts?

**Comment by DrPeterVanNostrand** [comment]
Yup, that makes sense to me.

**Comment by DrPeterVanNostrand** [comment]
@igorbarinov I can't delete the old repo with my "member" level privileges, either you or someone with admin level privileges has to.
