### ISSUE TITLE
thread 'main' panicked  error  while searching for threshold notifications 

### ISSUE THREAD

**Issue by 6proof** [poanetwork/poa-governance-notifications#13]
Both before and after compiling from source on fresh nodes (both Debian9 and Ubuntu 16.04), threshold notification queries cause a panic - please see following:
```
 target/release/poagov --sokol --v2 --threshold --start=5936000 --limit=3
Dec 05 21:23:43.361 INFO starting poagov...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This error seems to only occur with --threshold or -t flag.  Testing on Sokol right now since Threshold ballot is currently active.  What can do to help test and fix?

**Comment by DrPeterVanNostrand** [comment]
Fixed as of `2489bbb` in `master`.
