### ISSUE TITLE
(Update) Add support for updated consensus contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-governance-notifications#6]
**Problem:** We have [updated consensus smart contracts](https://github.com/poanetwork/poa-network-consensus-contracts/tree/ec307069302fdf6647e8b1bdc13093960913b266/contracts) that are going to be deployed in `Sokol` network in the next few days.

**Solution:** Please check the code of the tool and add support for new contracts if needed. The [new contracts](https://github.com/poanetwork/poa-network-consensus-contracts/tree/ec307069302fdf6647e8b1bdc13093960913b266/contracts) are slightly different from [old ones](https://github.com/poanetwork/poa-network-consensus-contracts/tree/aa45e19ca50f7cae308c1281d950245b0c65182a/contracts), so some changes in the tool may need to be done.

**Comment by varasev** [comment]
Hi @DrPeterVanNostrand,

Please take a look at this issue.

**Comment by DrPeterVanNostrand** [comment]
Ok np, thanks for letting me know.
